// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace EmployeeApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirtName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "EkaCompany",
                            FirtName = "Ebubekir",
                            LastName = "Karakurt"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "EkaCompany",
                            FirtName = "Ali",
                            LastName = "Doğmuş"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "EkaCompany",
                            FirtName = "Mehmet",
                            LastName = "Dağ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
